# permissions for end users to edit gitopsclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopscluster-editor-role
rules:
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters/status
  verbs:
  - get
