# permissions for end users to view gitopsclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopscluster-viewer-role
rules:
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters/status
  verbs:
  - get
