on:
  push:
    branches-ignore:
      - "main"
    tags-ignore:
      - "*"

name: test
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      GO_CACHE_NAME: cache-go-modules
    steps:
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.go-build }}
            ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-${{ github.job }}-${{ env.GO_CACHE_NAME }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-${{ env.GO_CACHE_NAME }}-
      - name: Run unit tests
        run: |
          go version
          # Uncomment following line once the code has been added
          # make test